# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

 
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds:  ${{secrets.AZURE_CREDENTIALS}}  

    #  - name: Run Azure CLI commands
    #     uses: Azure/cli@v2
    #     with:
    #       azcliversion: latest
    #       inlineScript: |
    #         az deployment sub create \
    #           --name create-rg-deployment \
    #           --location eastus2 \
    #           --template-file ARM-templates/resourceGroup.json
      - name: Deploy ARM Template
        uses: Azure/arm-deploy@v0
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: nQ-Resource-Group
          template: ARM-templates/resourceGroup.json