name: armTemplateDeployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}  

      - name: Deploy ARM Template (Resource Group)
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: eastus2
          template: ARM-templates/resourceGroup.json
          deploymentName: create-rg-deployment

      - name: Deploy Storage Account ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: nQ-Resource-Group
          template: ARM-templates/storageaccount.json
          parameters: resourceGroupName=nQ-Resource-Group
          deploymentMode: Incremental
          deploymentName: nQ-Incremental-Deployment-Storage